apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jump
  name: jump
spec:
  replicas: 1
  minReadySeconds: 0
  selector:
    matchLabels:
      app: jump
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jump
    spec:
      containers:
        - image: milcamboo/jump:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          name: jump